### PR TITLE
GPC-151: Set Postgres to verify-full

### PR DESCRIPTION
**Pull request by olevett**
This builds on #55, but I want to check it works as Corretto first

### CODE REVIEW

**Review by ethanmills — APPROVED** [review]
I'm glad it's someone else's turn to break the database for a change 😄

**Comment by olevett** [comment]
This may not work, so I want to watch when it gets merged :)

**Review by Mjwillis — APPROVED** [review]
LGTM

**Comment by olevett** [comment]
image
This went badly

**Pull request merged**
